export default {
  // Actions
  CHANGE: "CHANGE",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  GET_STATIONS: "GET_STATIONS",
  CHECK_INIT: "CHECK_INIT",

  // Events
  EVENT_STATIONS_READY: "EVENT_STATIONS_READY",
  EVENT_VARIABLES_READY: "EVENT_VARIABLES_READY",
  EVENT_USER_READY: "EVENT_USER_READY"
};
